### PR TITLE
Fix CircleCI build config

### PR DESCRIPTION
**Pull request by jeroenvandijk**
I've updated the CircleCI config so it builds again. See [result for current master](https://app.circleci.com/pipelines/github/jeroenvandijk/vcr-clj/1/workflows/ede016d8-732d-4d20-a449-a577ebb55167/jobs/1) /  Build status

### CODE REVIEW

**Comment by gfredericks** [comment]
Thanks!

I merged this via a cherry-pick (since your commit was a bit odd, being based one commit behind master and then including my changelog change redundantly), but it seems like it's still failing. Do I need to change something in the circleci website?

**Comment by jeroenvandijk** [comment]
Ah I guess I had an outdated git history, commit looks weird indeed. Thanks for fixing it.

Regarding the build, for some reason CircleCI does build under my account. However I did see a deprecation warning of the image. By updating the image this is gone.

@gfredericks Maybe you can try updating the image with this commit #33 

See https://app.circleci.com/pipelines/github/jeroenvandijk/vcr-clj/3/workflows/089d6a7c-5046-4e05-ad7e-96655a650d34/jobs/3

**Comment by gfredericks** [comment]
Nope, not that either; seems like a github permissions issue, is there an auth step on github I need to perform?

```
Using SSH Config Dir '/home/circleci/.ssh'
git version 2.34.1
Cloning git repository
Cloning into '.'...
Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128
```

**Comment by jeroenvandijk** [comment]
Ah I see. I have been able to reproduce this error by removing the deploy key under settings. ([example](https://app.circleci.com/pipelines/github/jeroenvandijk/vcr-clj/3/workflows/172aef2e-1765-4b3f-8b9f-3702449a647f/jobs/6))

I think you need to (re-)add the deploy key for this project under [(your) settings here](https://app.circleci.com/settings/project/github/gfredericks/vcr-clj/ssh), like screenshot below

SSH_-_vcr-clj

**Comment by gfredericks** [comment]
That helped, looks like it's all sorted now. Thanks!

**Pull request closed without merging**
